Update ci_workflow.yml

diff --git a/.github/workflows/ci_workflow.yml b/.github/workflows/ci_workflow.yml
--- a/.github/workflows/ci_workflow.yml
+++ b/.github/workflows/ci_workflow.yml
@@ -11,7 +11,10 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Run script
-        run: ./run_shapes.sh > ./build/run.log 2>&1 || error "Script failed"
+        run: |
+          echo $PWD
+          ./run_shapes.sh > ./build/run.log 2>&1
+          realpath ./build/run.log
       - name: Upload log file on failure
         if: failure()
         uses: actions/upload-artifact@v3 
@@ -19,18 +22,18 @@ jobs:
           name: script-log-file
           path: build/script.log
 
-  docker:
-      runs-on: ubuntu-latest
-      steps: 
-        - uses: actions/checkout@v4
-        - name: Build Docker image
-          run: docker build . --file Dockerfile --tag image:ci_workflow || error "Failed to create image"
-        - name: Run Docker container
-          run: docker run --rm image:ci_workflow || error "Failed to run image"
-        - name: Upload log file on failure
-          if: failure()
-          uses: actions/upload-artifact@v3 
-          with:
-            name: docker-log-file
-            path: build/docker.log
+  # docker:
+  #     runs-on: ubuntu-latest
+  #     steps: 
+  #       - uses: actions/checkout@v4
+  #       - name: Build Docker image
+  #         run: docker build . --file Dockerfile --tag image:ci_workflow || error "Failed to create image"
+  #       - name: Run Docker container
+  #         run: docker run --rm image:ci_workflow || error "Failed to run image"
+  #       - name: Upload log file on failure
+  #         if: failure()
+  #         uses: actions/upload-artifact@v3 
+  #         with:
+  #           name: docker-log-file
+  #           path: build/docker.log
         
