Update ci_workflow.yml

diff --git a/.github/workflows/ci_workflow.yml b/.github/workflows/ci_workflow.yml
--- a/.github/workflows/ci_workflow.yml
+++ b/.github/workflows/ci_workflow.yml
@@ -12,7 +12,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: Run script
         run: |
-          { ./run_shapes.sh > ./build/run.log 2>&1 || echo "Script failed" && exit 1; }  
+          { ./run_shapes.sh > ./build/run.log 2>&1 || { echo "Script failed" && exit 1; }; }  
           cat ./build/run.log
       - name: upload-run-log-file
         uses: actions/upload-artifact@v3
@@ -24,7 +24,7 @@ jobs:
         uses: actions/upload-artifact@v3 
         with:
           name: script-log-file
-          path: build/f_script.log
+          path: ./build/f_script.log
 
   docker:
       runs-on: ubuntu-latest
@@ -32,14 +32,14 @@ jobs:
         - uses: actions/checkout@v4
         - name: Build Docker image
           run: |
-            { docker build . --file Dockerfile --tag image:ci_workflow || echo "Failed to create image" && exit 1; }
+            { docker build . --file Dockerfile --tag image:ci_workflow || { echo "Failed to create image" && exit 1; }; }
         - name: Run Docker container
           run: |
-            { docker run --rm image:ci_workflow || echo "Failed to run image" && exit 1; }
+            { docker run --rm image:ci_workflow || { echo "Failed to run image" && exit 1; }; }
         - name: Upload log file on failure
           if: failure()
           uses: actions/upload-artifact@v3 
           with:
             name: docker-log-file
-            path: build/f_docker.log
+            path: ./build/f_docker.log
         
